public enum Screens {

    MAIN, CUSTOMER_ACCESS, CUSTOMER_INVALID, CUSTOMER, CUSTOMER_ACCOUNTS, CUSTOMER_ACCOUNT_INFO,
    CUSTOMER_TRANSACTION_FROM, CUSTOMER_TRANSACTION_FROM_SAVINGS, CUSTOMER_TRANSACTION_TO,
    CUSTOMER_TRANSACTION_TO_INVALID, CUSTOMER_TRANSACTION_AMOUNT, CUSTOMER_TRANSACTION_AMOUNT_INVALID,
    CUSTOMER_TRANSACTION_SUCCESS, CUSTOMER_TRANSACTION_ILLEGAL_OVERDRAFT, CUSTOMER_TRANSACTION_NEGATIVE_AMOUNT,
    EMPLOYEE, EMPLOYEE_SEARCH, EMPLOYEE_SEARCH_NAME, EMPLOYEE_SEARCH_MATCHES, EMPLOYEE_SEARCH_IDNUMBER,
    EMPLOYEE_SEARCH_ACCOUNT, EMPLOYEE_SEARCH_NOMATCH, EMPLOYEE_CUSTOMER, EMPLOYEE_ACCOUNT, EMPLOYEE_INTEREST_RATE,
    EMPLOYEE_OVERDRAFT, EMPLOYEE_WITHDRAWAL, EMPLOYEE_DEPOSIT, NOT_ENOUGH_CASH, ADMIN, ADMIN_STATUS;

}
